name: "Deploy with Firebase Functions"

on: 
  workflow_dispatch:
    
  push:
    branches:
      - main
      - develop
      
jobs: 
  compile:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          
        # Cache para que cargue mas rapido  
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Clean instalation sin console.log, para que vaya mas rapido.
      - name: Install Dependencies
        run: npm ci --silent

      # Firebase deploy
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.CORN_SECRET }}

