name: "Deploy with Firebase Functions"

on: 
  workflow_dispatch:
    
  push:
    branches:
      - main
      - develop
      
jobs: 
  compile:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout
        uses: ctions/checkout@v3
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          
      - name: Install
        run: |
          npm ci
          npm install
        working-directory: .
        
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: firebase login

      - name: Deploy Firebase Functions
        run: firebase deploy --only functions
  

